version: '3.7'
services:
  nsp-db:
    image: mysql:8.0.19
    container_name: nsp-db
    environment:
      MYSQL_DATABASE: ${DATABASE_DB}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    restart: unless-stopped
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - nsp-db-volume:/var/lib/mysql
    networks:
      - nsp-network

  nsp-ws:
    build:
      context: docker/php
    container_name: nsp-ws
    volumes:
      - ./ws:/var/www/vhosts/ws
    working_dir: /var/www/vhosts/ws
    env_file:
      - ./.env
    networks:
      nsp-network:
        aliases:
          - nsp-ws

  nsp-ws-nginx:
    image: nginx:latest
    container_name: nsp-ws-nginx
    ports:
      - "80:80"
    depends_on:
      - nsp-ws
    networks:
      - nsp-network
    volumes:
      - ./docker/nginx/conf/www-ws:/etc/nginx/conf.d/default.conf
      - ./ws:/var/www/vhosts/ws

  nsp-app:
    build: docker/app
    container_name: nsp-app
    hostname: nsp-app
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./app:/client
    networks:
      nsp-network:
        aliases:
          - nsp-app
    ports:
      - "8080:3000"
    stdin_open: true

volumes:
  nsp-db-volume:
  ws:
  app:
  kit:
networks:
  nsp-network: